name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Lab05.sln
    - name: Build
      run: dotnet build --no-restore ./Lab05.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Lab05.sln
      
      - name: zip
      uses: papeloto/action-zip@v1
      with: 
      files: /home/runner/work/Lab005/Lab005/Lab05/bin/Debug/net5.0/publish
      dest: lab05.zip
